apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apidoc-ingress
  namespace: apidoc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.apidoc.example.com
      secretName: apidoc-tls
  rules:
    - host: api.apidoc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apidoc-server
                port:
                  number: 80
