"""Tests for api endpoints — generated by apidoc testgen."""
import pytest
import httpx


class TestApiTests:

    def test_get__users_happy_path(self, client):
        """Happy path: GET /users"""
        r = client.get("/users")
        assert r.status_code == 200


    def test_get__users__user_id_happy_path(self, client):
        """Happy path: GET /users/{user_id}"""
        r = client.get(f"/users/{1}")
        assert r.status_code == 200

