"""pytest test-file generator plugin."""
from __future__ import annotations
import re
from pathlib import Path
from typing import Any
from apidoc.plugins import TestGenPlugin

class PytestTestGenPlugin(TestGenPlugin):
    def generate(self, spec: dict[str, Any], output_dir: str,
                 base_url: str, options: dict[str, Any]) -> list[str]:
        out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
        created: list[str] = []
        conf = out / "conftest.py"
        conf.write_text(self._conftest(base_url), encoding="utf-8")
        created.append(str(conf))

        ops_by_tag: dict[str, list[dict]] = {}
        for path_str, path_item in spec.get("paths", {}).items():
            for method, op in path_item.items():
                if method.upper() not in ("GET","POST","PUT","PATCH","DELETE"): continue
                if not isinstance(op, dict): continue
                tags = op.get("tags", ["api"]); tag = tags[0] if tags else "api"
                ops_by_tag.setdefault(tag, []).append({
                    "method": method.upper(), "path": path_str, "operation": op,
                    "has_security": bool(op.get("security") or spec.get("security")),
                    "has_body": "requestBody" in op,
                })
        for tag, ops in ops_by_tag.items():
            fname = f"test_{re.sub(chr(91)+chr(94)+'a-z0-9'+chr(93), chr(95), tag.lower())}.py"
            fp = out / fname
            fp.write_text(self._test_file(tag, ops), encoding="utf-8")
            created.append(str(fp))
        return created

    def _conftest(self, base_url: str) -> str:
        return f'''"""Shared fixtures."""
import pytest
import httpx

BASE_URL = "{base_url}"

@pytest.fixture(scope="session")
def client():
    with httpx.Client(base_url=BASE_URL, timeout=10) as c:
        yield c

@pytest.fixture
def auth_headers():
    return {{"Authorization": "Bearer test-token"}}
'''

    def _test_file(self, tag: str, ops: list[dict]) -> str:
        cls = "".join(w.title() for w in re.split(r"[^a-zA-Z0-9]", tag)) + "Tests"
        lines = [f'''"""Tests for {tag} endpoints — generated by apidoc testgen."""''',
                 "import pytest", "import httpx", "", "",
                 f"class Test{cls}:"]
        for item in ops:
            m = item["method"]; p = item["path"]; op = item["operation"]
            op_id = op.get("operationId") or f"{m}_{p}"
            safe = re.sub(r"[^a-zA-Z0-9_]","_",op_id).strip("_")
            body = ', json={"key": "value"}' if item["has_body"] else ""
            sc = [c for c in op.get("responses",{"200":{}}).keys() if str(c).startswith("2")]
            exp = sc[0] if sc else "200"
            pc = self._path_call(p)
            lines += ["",
                      f"    def test_{safe}_happy_path(self, client):",
                      f'        """Happy path: {m} {p}"""',
                      f"        r = client.{m.lower()}({pc}{body})",
                      f"        assert r.status_code == {exp}", ""]
            if item["has_body"]:
                lines += [f"    def test_{safe}_missing_required(self, client):",
                          f'        """Negative: 400/422 without required fields."""',
                          f"        r = client.{m.lower()}({pc})",
                          f"        assert r.status_code in (400, 422)", ""]
            if item["has_security"]:
                lines += [f"    def test_{safe}_unauthorized(self, client):",
                          f'        """Auth: 401/403 without token."""',
                          f"        r = client.{m.lower()}({pc})",
                          f"        assert r.status_code in (401, 403)", ""]
        return "\n".join(lines) + "\n"

    def _path_call(self, path: str) -> str:
        import re
        params = re.findall(r"\{(\w+)\}", path)
        if not params: return f'"{path}"'
        result = path
        for p in params: result = result.replace("{"+p+"}", "{1}")
        return f'f"{result}"'
